"""
Publishing actions for generated changelogs:

- publish a GitHub Release for the changelog's tag
- commit/update CHANGELOG.md in the target repository
"""
from __future__ import annotations

import logging

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.security import decrypt_api_key
from app.models.changelog import Changelog as ChangelogModel
from app.models.repo import Repository
from app.models.user import User
from app.services.github import GitHubClient
from app.config import settings

logger = logging.getLogger(__name__)

CHANGELOG_PATH = "CHANGELOG.md"


def _client() -> GitHubClient:
    return GitHubClient(
        client_id=settings.github_client_id or "",
        client_secret=settings.github_client_secret or "",
    )


async def _user_token(db: AsyncSession, user_id: str) -> str:
    result = await db.get(User, user_id)
    if result is None or not result.github_token:
        raise ValueError("No GitHub token available for this user")
    return decrypt_api_key(result.github_token)


def _release_body(changelog: ChangelogModel) -> str:
    return changelog.raw_markdown or "*No changelog content.*"


async def publish_release(
    changelog: ChangelogModel, repo: Repository, db: AsyncSession
) -> dict[str, str]:
    """Create a GitHub Release for the changelog. Returns {tag, release_url}."""
    token = await _user_token(db, changelog.user_id)
    tag = changelog.to_tag or changelog.version
    if not tag or tag.startswith("HEAD"):
        raise ValueError(
            "This changelog has no tag — releases need a version tag. "
            "Create a tag in GitHub and regenerate first."
        )
    client = _client()
    data = await client.create_release(
        token=token,
        full_name=repo.full_name,
        tag=tag,
        name=changelog.version or tag,
        body=_release_body(changelog),
    )
    logger.info("Published release %s for %s", tag, repo.full_name)
    return {"tag": tag, "release_url": data.get("html_url", "")}


async def commit_changelog_file(
    changelog: ChangelogModel, repo: Repository, db: AsyncSession
) -> dict[str, str]:
    """
    Create or update CHANGELOG.md in the target repository with the
    generated markdown. Returns {branch, file, commit_sha}.
    """
    token = await _user_token(db, changelog.user_id)
    if not changelog.raw_markdown:
        raise ValueError("Changelog has no content to commit")

    branch = repo.default_branch or "main"
    header = (
        f"# Changelog — {changelog.version or changelog.to_tag or 'Unreleased'}\n\n"
        f"_{changelog.summary or 'Generated by Release Notes'}_\n\n"
    )
    content = f"{header}{changelog.raw_markdown}\n"

    client = _client()
    data = await client.get_or_create_file_commit(
        token=token,
        full_name=repo.full_name,
        branch=branch,
        path=CHANGELOG_PATH,
        content=content,
        commit_message=(
            f"docs: update CHANGELOG.md for "
            f"{changelog.version or changelog.to_tag or 'release'}"
        ),
    )
    sha = (data.get("commit") or {}).get("sha", "")
    logger.info(
        "Committed %s to %s@%s (%s)",
        CHANGELOG_PATH, repo.full_name, branch, sha[:7] if sha else "?",
    )
    return {"branch": branch, "file": CHANGELOG_PATH, "commit_sha": sha}