"""
Slack webhook notification provider.

Ported from TypeScript src/notify/slack.ts
"""
from __future__ import annotations

import httpx
import re

from app.services.notify.base import NotifyProviderInterface


class SlackProvider(NotifyProviderInterface):
    name = "Slack"

    def __init__(self, webhook_url: str, channel: str | None = None) -> None:
        self.webhook_url = webhook_url
        self.channel = channel

    async def send(
        self,
        from_addr: str = "",
        to_addr: str = "",
        subject: str = "",
        body: str = "",
    ) -> None:
        # Build a Slack Block Kit message
        blocks: list[dict] = [
            {"type": "header", "text": {"type": "plain_text", "text": subject, "emoji": True}},
            {"type": "divider"},
        ]

        sections = re.split(r"(?=^## )", body, flags=re.MULTILINE)
        for section in sections:
            trimmed = section.strip()
            if not trimmed or trimmed.startswith("---"):
                continue

            lines = [l for l in trimmed.split("\n") if l.strip()]

            # Heading
            if lines:
                heading_match = re.match(r"^#{1,2}\s+(.*)", lines[0])
                if heading_match:
                    blocks.append({
                        "type": "section",
                        "text": {"type": "mrkdwn", "text": f"*{heading_match.group(1)}*"},
                    })

            # Bullet items
            bullets = [re.sub(r"^- ", "", l) for l in lines if l.startswith("- ")]
            if bullets:
                for i in range(0, len(bullets), 10):
                    chunk = bullets[i:i + 10]
                    blocks.append({
                        "type": "section",
                        "text": {"type": "mrkdwn", "text": "\n".join(f"• {b}" for b in chunk)},
                    })

        blocks.append({"type": "divider"})
        blocks.append({
            "type": "context",
            "elements": [{"type": "mrkdwn", "text": "🤖 *Auto-generated by auto-changelog*"}],
        })

        payload: dict = {"text": subject, "blocks": blocks}
        if self.channel:
            payload["channel"] = self.channel

        async with httpx.AsyncClient() as client:
            response = await client.post(
                self.webhook_url,
                json=payload,
                headers={"Content-Type": "application/json"},
            )
            response.raise_for_status()