"""
Commit-based changelog provider — parses conventional commit messages
without needing any LLM API key.

Ported from TypeScript src/llm/commit.ts
"""
from __future__ import annotations

import re
from collections import OrderedDict

from app.services.llm.base import LlmProviderInterface

# ── Conventional commit regex ──
CONVENTIONAL_RE = re.compile(
    r"^(feat|fix|docs|chore|refactor|perf|test|ci|build|style|revert)"
    r"(?:\([^)]*\))?!?:\s*(.*)$",
    re.IGNORECASE | re.MULTILINE,
)
BREAKING_FOOTER_RE = re.compile(r"^BREAKING[-\s]CHANGE:\s*(.*)$", re.IGNORECASE | re.MULTILINE)
BREAKING_EXCLAMATION_RE = re.compile(r"^.*!:")

TYPE_MAP = {
    "feat": "feature", "fix": "fix", "docs": "docs",
    "chore": "chore", "refactor": "refactor", "perf": "perf",
    "test": "chore", "ci": "chore", "build": "chore",
    "style": "chore", "revert": "other",
}

SECTION_LABELS = {
    "feature": "🚀 Features", "fix": "🐛 Bug Fixes", "docs": "📖 Documentation",
    "perf": "⚡ Performance", "refactor": "🛠 Refactors",
    "chore": "🧹 Chores", "other": "🔧 Other Changes",
}


def _categorize_commit(message: str) -> dict | None:
    """Parse a conventional commit message into a categorized entry."""
    trimmed = message.strip()
    is_breaking = bool(BREAKING_EXCLAMATION_RE.match(trimmed)) or bool(BREAKING_FOOTER_RE.search(trimmed))

    match = CONVENTIONAL_RE.match(trimmed)
    if match:
        prefix, desc = match.group(1), match.group(2)
        description = desc or trimmed
        entry_type = TYPE_MAP.get(prefix.lower(), "other")
        if is_breaking:
            description = f"[BREAKING] {description}"
        return {"type": entry_type, "description": description, "is_breaking": is_breaking}

    return {"type": "other", "description": trimmed, "is_breaking": False}


def _guess_version(from_tag: str, entries: list[dict]) -> str:
    """Bump semver based on breaking changes and features."""
    has_breaking = any(e["is_breaking"] for e in entries)
    has_feature = any(e["type"] == "feature" for e in entries)
    ver_match = re.search(r"(\d+)\.(\d+)\.(\d+)", from_tag)
    if ver_match:
        major, minor, patch = map(int, ver_match.groups())
        if has_breaking:
            major += 1; minor = 0; patch = 0
        elif has_feature:
            minor += 1; patch = 0
        else:
            patch += 1
        return f"v{major}.{minor}.{patch}"
    return f"{from_tag}-next"


def _build_markdown(from_tag: str, to_tag: str, entries: list[dict]) -> str:
    """Build a nicely formatted changelog markdown string."""
    new_version = _guess_version(from_tag, entries)
    sections: OrderedDict[str, list[str]] = OrderedDict()
    breaking_descriptions: list[str] = []

    for entry in entries:
        if entry["is_breaking"]:
            desc = re.sub(r"^\[BREAKING\]\s*", "", entry["description"])
            breaking_descriptions.append(desc)
            continue
        label = SECTION_LABELS.get(entry["type"], "🔧 Other Changes")
        if label not in sections:
            sections[label] = []
        sections[label].append(entry["description"])

    lines: list[str] = [
        f"# Changelog — {new_version}",
        "",
        f"*Changes compared to {from_tag}*",
        "",
    ]

    if breaking_descriptions:
        lines.append("## 💥 Breaking Changes")
        for desc in breaking_descriptions:
            lines.append(f"- {desc}")
        lines.append("")

    for heading, items in sections.items():
        if not items:
            continue
        lines.append(f"## {heading}")
        for item in items:
            lines.append(f"- {item}")
        lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("*Auto-generated by auto-changelog (commit-based mode)*")
    return "\n".join(lines)


class CommitProvider(LlmProviderInterface):
    """Parse conventional commits without any API key."""

    name = "Commit-based (conventional commits)"

    async def generate(self, prompt: str, system_prompt: str | None = None) -> str:
        # Extract the commit summary section from the prompt
        commit_section = prompt.split("## Commit Summary (messages)")[1] if "## Commit Summary (messages)" in prompt else None
        if commit_section is None or "##" in commit_section:
            # Split at next ##
            parts = prompt.split("## Commit Summary (messages)")
            commit_section = parts[1] if len(parts) > 1 else ""
            commit_section = commit_section.split("##")[0] if "##" in commit_section else commit_section

        if not commit_section or not commit_section.strip():
            return self._fallback("(no commits found)")

        tag_match = re.search(
            r"Generate a changelog for the changes between (.+?) and (.+?)\.",
            prompt,
        )
        from_tag = tag_match.group(1) if tag_match else "previous"
        to_tag = tag_match.group(2) if tag_match else "current"

        # Parse commit lines
        commit_lines = [
            l.strip() for l in commit_section.split("\n")
            if l.strip() and l.strip().startswith("[")
        ]

        if not commit_lines or commit_lines == ["(no commits found between these refs)"]:
            return self._fallback("(no commits found)")

        entries: list[dict] = []
        for line in commit_lines:
            hash_match = re.match(r"^\[([a-f0-9]+)\]\s*.*?[—–]\s*(.*)$", line)
            if not hash_match:
                continue
            _sha, message = hash_match.groups()
            entry = _categorize_commit(message)
            if entry:
                entries.append(entry)

        return _build_markdown(from_tag, to_tag, entries)

    @staticmethod
    def _fallback(reason: str) -> str:
        return "\n".join([
            "# Changelog",
            "",
            f"*{reason}*",
            "",
            "---",
            "",
            "*Auto-generated by auto-changelog (commit-based mode)*",
        ])